
AllCops:
  Exclude:
    - "README.md"
    - "Guardfile"
    - "Rakefile"
    - "./spec/spec_helper.rb"

  DisplayCopNames: true

Metrics/LineLength:
  Max: 999
Metrics/MethodLength:
  Max: 999
Metrics/AbcSize:
  Max: 50
Metrics/ClassLength:
  Max: 999
Metrics/BlockLength:
  ExcludedMethods: ['describe']
  Max: 30
Metrics/CyclomaticComplexity:
  Max: 15
Metrics/PerceivedComplexity:
  Max: 15
Metrics/ModuleLength:
  Max: 999


Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/EachForSimpleLoop:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/DefWithParentheses:
  Enabled: false
Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Layout/ExtraSpacing:
  AllowForAlignment: false
Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented